apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: "default,dev,myndighet-stub,caching-enabled,wc-hsa-stub, fake, saml"
  SPRING_DATASOURCE_URL: "jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${database.name}?useSSL=false"
  REDIS_PORT: "${redis.service.port}"
  REDIS_HOST: "${redis.service.host}"
  IB_HOST_URL: "https://intygsbestallning-demo-demointyg.app-test1.ind-ocp.sth.basefarm.net"
kind: ConfigMap
metadata:
  name: intygsbestallning-demo-configmap-envvar
type: Opaque
