apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: "default,demo,myndighet-stub,caching-enabled,wc-hsa-stub, fake, saml"
  SPRING_DATASOURCE_URL: "jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${database.name}?useSSL=false"
  REDIS_PORT: "${redis.service.port}"
  REDIS_HOST: "${redis.service.host}"
  NTJP_BASE_URL: "http://localhost:8080/services/stubs"
  NTJP_WS_CERTIFICATE_TYPE: "PKCS12"
  NTJP_WS_CERTIFICATE_FILE: "${certificate.folder}/localhost.p12"
  NTJP_WS_TRUSTSTORE_TYPE: "JKS"
  NTJP_WS_TRUSTSTORE_FILE: "${certificate.folder}/truststore.jks"
  PUTJANST_LOGICALADDRESS: "SE165565594230-1000"
  INFRASTRUCTURE_DIRECTORY_LOGICALADDRESS: ""
  INERA_SAML_KEYSTORE_FILE: "file:///${certificate.folder}/localhost.p12"
  INERA_SAML_KEYSTORE_ALISA: "localhost"
  IB_HOST_URL: "https://intygsbestallning-demo-demointyg.app-test1.ind-ocp.sth.basefarm.net"
  CONFIG_FOLDER: "/opt/intygsbestallning-demo/config"
  CERTIFICATE_FOLDER: "/opt/intygsbestallning-demo/env"
  MAIL_HOST: "${ib.host.url}"
  ACTIVEMQ_BROKER_URL: "${activemq.amq.tcp.port}?jms.nonBlockingRedelivery=true&jms.redeliveryPolicy.maximumRedeliveries=3&jms.redeliveryPolicy.maximumRedeliveryDelay=6000&jms.redeliveryPolicy.initialRedeliveryDelay=4000&jms.redeliveryPolicy.useExponentialBackOff=true&jms.redeliveryPolicy.backOffMultiplier=2"
kind: ConfigMap
metadata:
  name: intygsbestallning-demo-configmap-envvar
type: Opaque
