apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: "default,myndighet-stub,caching-enabled,wc-hsa-stub,dev-security"
  SPRING_DATASOURCE_URL: "jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${database.name}"
  REDIS_PORT: "${redis.service.port}"
  REDIS_HOST: "${redis.service.host}"
kind: ConfigMap
metadata:
  name: intygsbestallning-demo-configmap-envvar
type: Opaque
