apiVersion: v1
data:
  SPRING_PROFILES_ACTIVE: "default,myndighet-stub,dev,caching-enabled,wc-hsa-stub,dev-security"
kind: ConfigMap
metadata:
  name: intygsbestallning-demo-configmap-envvar
type: Opaque
