apiVersion: v1
stringData:
  SPRING_DATASOURCE_USERNAME: "intygsbestallning"
  SPRING_DATASOURCE_PASSWORD: "intygsbestallning"
  REDIS_PASSWORD: "redis"
kind: Secret
metadata:
  name: intygsbestallning-demo-secret-envvar
type: Opaque
