config:
  folder: dummy

certificate:
  folder: ${config.folder}

ntjp:
  base:
    url: http://localhost:8080/services/stubs
  ws:
    certificate:
      file: file:///${certificate.folder}/localhost.p12
      password: password
      type: PKCS12
    truststore:
      file: file:///${certificate.folder}/truststore.jks
      password: password
      type: JKS

infrastructure:
  directory:
    logicalAddress:

ib:
  server: localhost:8990
  host:
    url: http://localhost:8080

putjanst:
  logicaladdress: PUDEV

inera:
  saml:
    sp:
      metadata: ${config.folder}/sp-inera.xml
    idp:
      metadata: ${config.folder}/idp-inera.xml
    keystore:
      password: password
      file: file:///${certificate.folder}/localhost.p12
      alias: localhost

activemq:
  broker:
    url: tcp://localhost:61616?jms.nonBlockingRedelivery=true&jms.redeliveryPolicy.maximumRedeliveries=3&jms.redeliveryPolicy.maximumRedeliveryDelay=6000&jms.redeliveryPolicy.initialRedeliveryDelay=4000&jms.redeliveryPolicy.useExponentialBackOff=true&jms.redeliveryPolicy.backOffMultiplier=2
    #url: vm://localhost?broker.persistent=false
    username: admin
    password: admin
pdl:
  logging:
    system-id: dev-id
    system-name: dev-name
    queue-name: ib.pdllogging.queue

mailsender:
  maximum-redeliveries: 5
  redelivery-delay: 100
  back-off-multiplier: 1
  queue-name: ib.mailsender.queue

bestallning:
  paminnelse:
    cron: 0 1/5 * * * MON-FRI

# Mail notifications
mail:
  host: http://localhost:8080

