ntjp:
  base:
    url: localhost:8080/services/stubs

infrastructure:
  directory:
    logicalAddress:

resources:
  folder: ${resource.dir}

putjanst:
  logicaladdress: PUDEV

persistence:
  bootstrap:
    vardenhet-directory: classpath*:bootstrap/vardenhet/
    bestallning-directory: classpath*:bootstrap/bestallning/
