resources:
  folder: "classpath:"

# Disable spring boot default error handling
server:
  port: 8080
  use-forward-headers: true
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m
spring:
  datasource:
    url: jdbc:h2:mem:dataSource;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/changelog/db-changelog-master.xml
  profiles:
    active: default, myndighet-stub, dev, caching-enabled, wc-hsa-stub, fake, saml
  main:
    allow-bean-definition-overriding: true
  session:
    store-type: redis


# Mail notifications
mail:
  text-resource-path: ${resources.folder}/intygsbestallning/texts/mail/*.xml
  server-host: mail-server-host
  admin: ib-notifications@inera.se
  from: ib-notifications@inera.se
  username:
  password:
  protocol: smtps
  port: 25
  defaultEncoding: UTF-8
  auth: true
  starttls-enable: true
  debug: false

bestallning:
  text-resource-path: ${resources.folder}/intygsbestallning/texts/bestallning/*.xml
  host: ${ib.host.url}
  paminnelse:
    cron: DUMMY
#AUTH
authorities:
  configuration:
    file: ${resources.folder}/intygsbestallning/authorities.yaml
features:
  configuration:
    file: ${resources.folder}/intygsbestallning/features.yaml

#HSA integration
infrastructure:
  directory:
    employee:
      getemployee:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/employee/GetEmployeeIncludingProtectedPerson/1/rivtabp21
    organization:
      gethealthcareunitmembers:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/organization/GetHealthCareUnitMembers/1/rivtabp21
      gethealthcareunit:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/organization/GetHealthCareUnit/1/rivtabp21
      getunit:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/organization/GetUnit/1/rivtabp21
    authorizationmanagement:
      getcredentialsforpersonincludingprotectedpersonresponderinterface:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/authorizationmanagement/GetCredentialsForPersonIncludingProtectedPerson/1/rivtabp21

putjanst:
  endpoint:
    url: ${ntjp.base.url}/strategicresourcemanagement/persons/person/GetPersonsForProfile/3/rivtabp21

#Cache settings
pu:
  cache:
    expiry: 86400

hsa:
  healhcareunitmembers:
    cache:
      expiry: 86400
  healthcareunit:
    cache:
      expiry: 86400
  unit:
    cache:
      expiry: 86400
  stub:
    additional:
      identities:
        folder: ${java.io.tmpdir}

redis:
  sentinel:
    master:
      name: master
  password:
  cache:
    default_entry_expiry_time_in_seconds: 86400
  port: 6379
  host: 127.0.0.1


activemq:
  broker:
    url: vm://localhost?broker.persistent=false
    username:
    password:

pdl:
  logging:
    system-id: sys-id
    system-name: sys-name
    queue-name: ib.pdllogging.queue

cxf:
  path: /services

integration:
  myndighet-integration-url: https://tjp.nordicmedtest.se/intyg_ib/
  respond-to-order-url: intygsbestallning/certificate/order/RespondToOrder/1/rivtabp21
  certificate-type-code-system: fe11ea2d-9c5f-4786-b98f-bd5e6c93ea72
  source-system-hsa-id: dev-hsaid

################################################
#
# Säkerhetstjänst SAML configuration
#
################################################
inera:
  saml:
    sp:
      metadata: ${config.folder}/sp-inera.xml
    idp:
      metadata: ${config.folder}/idp-inera.xml
    keystore:
      file: file:${certificate.folder}/login.certificate.jks
      alias: verifiering.rehabstod.intygstjanster.sjunet.org
      password: dummy

# Bootstrap
persistence:
  bootstrap:
    bestallning-directory: classpath*:bootstrap/bestallning/
