config:
  folder: dummy

certificate:
  folder: ${config.folder}

spring:
  h2:
    console:
      enabled: true

ntjp:
  base:
    url: http://localhost:8080/services/stubs
  ws:
    certificate:
      file: ${certificate.folder}/localhost.p12
      password: password
      type: PKCS12
    truststore:
      file: ${certificate.folder}/truststore.jks
      password: password
      type: JKS

infrastructure:
  directory:
    logicalAddress:

ib:
  server: localhost:8990
  host:
    url: http://localhost:8080

putjanst:
  logicaladdress: PUDEV

inera:
  saml:
    sp:
      metadata: ${config.folder}/sp-inera.xml
    idp:
      metadata: ${config.folder}/idp-inera.xml
    keystore:
      password: password
      file: file:///${certificate.folder}/localhost.p12
      alias: localhost

activemq:
  broker:
    url: vm://localhost?broker.persistent=false
    username:
    password:

pdl:
  logging:
    system-id: dev-id
    system-name: dev-name

# Mail notifications
mail:
  host: ${ib.host.url}

