resources:
  folder: ${resources.dir}
config:
  folder: ${config.dir}

spring:
  datasource:
    url: jdbc:h2:mem:dataSource;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/changelog/db-changelog-master.xml
  profiles:
    active: default, myndighet-stub, dev, caching-enabled, wc-hsa-stub, dev-security
  main:
    allow-bean-definition-overriding: true


# Mail notifications
mail:
  text-resource-path: ${resources.folder}/texter/mail/
  host: ib-host
  admin: ib-notifications@inera.se
  from: ib-notifications@inera.se
  username:
  password:
  protocol: smtps
  defaultEncoding: UTF-8
  smtps:
    auth: true
    starttls.enable: true
    debug: false

bestallning:
  text-resource-path: ${resources.folder}/texter/bestallning/
  image-resource-path: ${resources.folder}/bilder/bestallning/

#AUTH
authorities:
  configuration:
    file: ${resources.folder}/security/authorities.yaml
features:
  configuration:
    file: ${resources.folder}/security/features.yaml

#HSA integration
infrastructure:
  directory:
    employee:
      getemployee:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/employee/GetEmployeeIncludingProtectedPerson/1/rivtabp21
    organization:
      gethealthcareunitmembers:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/organization/GetHealthCareUnitMembers/1/rivtabp21
      gethealthcareunit:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/organization/GetHealthCareUnit/1/rivtabp21
      getunit:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/organization/GetUnit/1/rivtabp21
    authorizationmanagement:
      getcredentialsforpersonincludingprotectedpersonresponderinterface:
        endpoint:
          url: ${ntjp.base.url}/infrastructure/directory/authorizationmanagement/GetCredentialsForPersonIncludingProtectedPerson/1/rivtabp21

pdlLogging:
  systemName: Intygsbestallning
  systemId: 12345

putjanst:
  endpoint:
    url: ${ntjp.base.url}/strategicresourcemanagement/persons/person/GetPersonsForProfile/3/rivtabp21

#Cache settings
pu:
  cache:
    expiry: 86400

hsa:
  healhcareunitmembers:
    cache:
      expiry: 86400
  healthcareunit:
    cache:
      expiry: 86400
  unit:
    cache:
      expiry: 86400
  stub:
    additional:
      identities:
        folder: ${java.io.tmpdir}

redis:
  sentinel:
    master:
      name: master
  password:
  cache:
    default_entry_expiry_time_in_seconds: 86400
  port: 6379
  host: 127.0.0.1


activemq:
  broker:
    url: vm://localhost?broker.persistent=false
    username:
    password:

cxf:
  path: /services

integration:
  myndighet-integration-url: https://tjp.nordicmedtest.se/intyg_ib/
  respond-to-order-url: intygsbestallning/certificate/order/RespondToOrder/1/rivtabp21
  certificate-type-code-system: b64ea353-e8f6-4832-b563-fc7d46f29548
  source-system-hsa-id: dev-hsaid

pdl:
  system-id: dev-id
  system-name: dev-name

################################################
#
# Säkerhetstjänst SAML configuration
#
################################################
sakerhetstjanst:
  saml:
    responseSkew: 300
    truststore:
      file: file:${certificate.folder}/ntjp.truststore.jks
    entityId: ${ib.host.url}
    entityBaseUrl: ${ib.host.url}
    idp:
      metadata:
        url: https://idp2.acctest.sakerhetstjanst.inera.se:443/idp/saml
    keystore:
      file: file:${certificate.folder}/login.certificate.jks
      alias: verifiering.rehabstod.intygstjanster.sjunet.org

