spring:
  datasource:
    url: jdbc:h2:mem:dataSource;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create

  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:/changelog/db-changelog-master.yaml
