spring:
  datasource:
    url: jdbc:h2:mem:dataSource;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create

  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:/changelog/db-changelog-master.xml
# Mail notifications
mail:
  host:
  admin: ib-notifications@inera.se
  from: ib-notifications@inera.se

  username:
  password:
  protocol: smtps
  defaultEncoding: UTF-8
  smtps:
    auth: true
    starttls.enable: true
    debug: false

activemq:
  broker:
    url: vm://localhost?broker.persistent=false
    username:
    password:

