resources:
  folder: ${resources.dir}

spring:
  datasource:
    url: jdbc:h2:mem:dataSource;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create
  h2:
    console:
      enabled: true

  liquibase:
    change-log: classpath:/changelog/db-changelog-master.xml

  profiles:
    active: default, myndighet-stub

# Mail notifications
mail:
  text-resource-path: ${resources.folder}/mail/texter/
  host: ib-host
  admin: ib-notifications@inera.se
  from: ib-notifications@inera.se

  username:
  password:
  protocol: smtps
  defaultEncoding: UTF-8
  smtps:
    auth: true
    starttls.enable: true
    debug: false

activemq:
  broker:
    url: vm://localhost?broker.persistent=false
    username:
    password:

cxf:
  path: /services

integration:
  myndighet-integration-url: https://tjp.nordicmedtest.se/intyg_ib/
  respond-to-order-url: intygsbestallning/certificate/order/RespondToOrder/1/rivtabp21
  certificate-type-code-system: b64ea353-e8f6-4832-b563-fc7d46f29548
  source-system-hsa-id: dev-hsaid

pdl:
  system-id: dev-id
  system-name: dev-name
