config:
  folder: dummy

certificate:
  folder: dummy

ntjp:
  base:
    url: http://localhost:8080/services/stubs

infrastructure:
  directory:
    logicalAddress:
ib:
  server: localhost:8990
  host:
    url: http://localhost:8080

putjanst:
  logicaladdress: PUDEV

sakerhetstjanst:
  saml:
    keystore:
      password: dummy

activemq:
  broker:
    url: vm://localhost?broker.persistent=false
    password:
    username:

mailsender:
  maximum_redeliveries: 5
  redelivery_delay: 100
  back_off_multiplier: 1
  queue_name: ib.mailsender.queue

bestallning:
  paminnelse:
    cron: 0 1/5 * * * MON-FRI