config:
  folder: dummy

certificate:
  folder: dummy

ntjp:
  base:
    url: http://localhost:8080/services/stubs

infrastructure:
  directory:
    logicalAddress:
ib:
  server: localhost:8990
  host:
    url: http://localhost:8080

putjanst:
  logicaladdress: PUDEV

persistence:
  bootstrap:
    vardenhet-directory: classpath*:bootstrap/vardenhet/
    bestallning-directory: classpath*:bootstrap/bestallning/

sakerhetstjanst:
  saml:
    keystore:
      password: dummy

activemq:
  broker:
    url: vm://localhost?broker.persistent=false
    password:
    username:

mailsender:
  maximum-redeliveries: 5
  redelivery-delay: 100
  back-off-multiplier: 1
  queue-name: ib.mailsender.queue

bestallning:
  paminnelse:
    cron: 0 1/5 * * * MON-FRI