ntjp:
  base:
    url: localhost:8080/services/stubs

infrastructure:
  directory:
    logicalAddress:

resources:
  folder: ${resource.dir}

putjanst:
  logicaladdress: PUDEV

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
